import { Profile } from "@/types";

export const sampleProfiles: Profile[] = [
  {
    id: "1",
    name: "מאיה",
    age: 27,
    city: "תל אביב",
    bio: "מעצבת גרפית שאוהבת אמנות, קפה בוקר וטיולים בטבע. מחפשת מישהו עם חיוך טוב ושיחה מעניינת.",
    interests: ["אמנות", "צילום", "טיולים", "בישול"],
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80",
    distance: 2,
    online: true,
    authMethod: "google",
    verified: true,
  },
  {
    id: "2",
    name: "רון",
    age: 31,
    city: "ירושלים",
    bio: "מהנדס תוכנה ביום, גיטריסט בלילה. אוהב מוזיקת אינדי, סרטים וכוס יין טובה.",
    interests: ["מוזיקה", "סרטים", "טכנולוגיה", "יין"],
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80",
    distance: 5,
    online: false,
    authMethod: "sms",
    verified: true,
  },
  {
    id: "3",
    name: "שירה",
    age: 25,
    city: "חיפה",
    bio: "סטודנטית לפסיכולוגיה, אוהבת כלבים, ספרים וימי שישי עם חברים. תמיד מחפשת את ההרפתקה הבאה.",
    interests: ["ספרים", "כלבים", "אופניים", "פסיכולוגיה"],
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80",
    distance: 8,
    online: true,
    authMethod: "facebook",
    verified: true,
  },
  {
    id: "4",
    name: "איתי",
    age: 29,
    city: "תל אביב",
    bio: "שף במסעדה קטנה. אוכל הוא התשוקה שלי, אבל אני גם אוהב לרוץ בשבת בבוקר ולצלול בים.",
    interests: ["בישול", "ריצה", "צלילה", "מסעדנות"],
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    distance: 3,
    online: false,
    authMethod: "email",
    verified: false,
  },
  {
    id: "5",
    name: "נועה",
    age: 26,
    city: "רעננה",
    bio: "וטרינרית שאוהבת חיות יותר מאנשים (רוב הזמן). אוהבת טיולים, ספרים ושקט בבית.",
    interests: ["חיות", "טיולים", "ספרים", "יוגה"],
    image: "https://images.unsplash.com/photo-1534528741775-54039ad24f0d?w=800&q=80",
    distance: 12,
    online: true,
    authMethod: "google",
    verified: true,
  },
  {
    id: "6",
    name: "עומר",
    age: 33,
    city: "הרצליה",
    bio: "יזם ומייסד סטארטאפ. אוהב גלישת גלים, קפה ושיחות עמוקות על החיים.",
    interests: ["גלישה", "סטארטאפים", "קפה", "פילוסופיה"],
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
    distance: 7,
    online: false,
    authMethod: "sms",
    verified: true,
  },
];